# -*- coding: utf-8 -*-
"""实现“模型一:相对特征变动率”的程序.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1poSLzvrQMjTClxYVKTemL5U54ZxgSr5q
"""

import cv2
import dlib
import math
import os
import urllib.request
import bz2
import glob
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# ==========================================
# 第一階段：自動下載與準備 dlib 模型
# ==========================================
dat_path = "shape_predictor_68_face_landmarks.dat"
if not os.path.exists(dat_path):
    print("📥 正在下載 dlib 68點模型 (約 60MB)...")
    bz2_path = dat_path + ".bz2"
    urllib.request.urlretrieve("http://dlib.net/files/shape_predictor_68_face_landmarks.dat.bz2", bz2_path)
    with bz2.BZ2File(bz2_path, "rb") as file, open(dat_path, "wb") as out:
        out.write(file.read())
    os.remove(bz2_path)
    print("✅ 模型準備就緒！")

detector = dlib.get_frontal_face_detector()
predictor = dlib.shape_predictor(dat_path)

# ==========================================
# 輔助函數區
# ==========================================
def draw_clear_text(img, text, position, font, scale, color, thickness):
    cv2.putText(img, text, position, font, scale, (0, 0, 0), thickness + 3, cv2.LINE_AA)
    cv2.putText(img, text, position, font, scale, color, thickness, cv2.LINE_AA)

def draw_med_pt(img, pt, color):
    cv2.circle(img, pt, 6, (0, 0, 0), -1, cv2.LINE_AA)
    cv2.circle(img, pt, 3, color, -1, cv2.LINE_AA)
    cv2.circle(img, pt, 1, (0, 0, 0), -1, cv2.LINE_AA)

# ==========================================
# 數學模型模組 (基於 Numpy 的標準化運算)
# ==========================================
def geometric_normalization(landmarks):
    pts = np.array([(landmarks.part(i).x, landmarks.part(i).y) for i in range(68)], dtype=np.float32)
    nose_tip = pts[30]
    pts_prime = pts - nose_tip
    left_eye_center = np.mean(pts_prime[36:42], axis=0)
    right_eye_center = np.mean(pts_prime[42:48], axis=0)
    d_pupil = np.linalg.norm(right_eye_center - left_eye_center)
    if d_pupil == 0: d_pupil = 1
    pts_double_prime = pts_prime / d_pupil
    dy = right_eye_center[1] - left_eye_center[1]
    dx = right_eye_center[0] - left_eye_center[0]
    theta_roll = np.arctan2(dy, dx)
    c, s = np.cos(-theta_roll), np.sin(-theta_roll)
    R = np.array(((c, -s), (s, c)))
    return np.dot(pts_double_prime, R.T)

def calculate_gri(norm_pts):
    face_length = np.linalg.norm(norm_pts[27] - norm_pts[8])
    face_width = np.linalg.norm(norm_pts[1] - norm_pts[15])
    r1 = face_length / face_width if face_width != 0 else 0
    mouth_width = np.linalg.norm(norm_pts[48] - norm_pts[54])
    nose_width = np.linalg.norm(norm_pts[31] - norm_pts[35])
    r2 = mouth_width / nose_width if nose_width != 0 else 0
    return np.mean([np.exp(-((r1 - 1.618)**2)), np.exp(-((r2 - 1.618)**2))])

def calculate_advanced_ai(norm_pts):
    symmetric_pairs = [(0, 16), (1, 15), (2, 14), (3, 13), (4, 12), (5, 11), (6, 10), (7, 9),
                       (36, 45), (37, 44), (38, 43), (39, 42), (40, 47), (41, 46),
                       (31, 35), (32, 34), (48, 54), (49, 53), (50, 52), (59, 55), (58, 56)]
    ai_sum = 0
    for l_idx, r_idx in symmetric_pairs:
        p_l = norm_pts[l_idx]
        p_r_real = norm_pts[r_idx]
        p_r_ideal = np.array([-p_l[0], p_l[1]])
        ai_sum += np.linalg.norm(p_r_ideal - p_r_real)
    return ai_sum

def calculate_pose_indices(norm_pts):
    d_left = np.linalg.norm(norm_pts[30] - norm_pts[1])
    d_right = np.linalg.norm(norm_pts[30] - norm_pts[15])
    yaw = abs(d_left - d_right) / (d_left + d_right) if (d_left + d_right) != 0 else 0
    h_upper = np.linalg.norm(norm_pts[27] - norm_pts[33])
    h_lower = np.linalg.norm(norm_pts[33] - norm_pts[8])
    pitch = h_lower / h_upper if h_upper != 0 else 0
    return yaw, pitch

def calculate_lci(gray_img, landmarks):
    img_h, img_w = gray_img.shape
    def get_val(idx): return float(gray_img[min(max(int(landmarks.part(idx).y), 0), img_h-1), min(max(int(landmarks.part(idx).x), 0), img_w-1)])
    l_center = np.mean([get_val(i) for i in range(27, 31)])
    l_edge = np.mean([get_val(i) for i in [2, 3, 13, 14]])
    if (l_center + l_edge) == 0: return 0
    return (l_center - l_edge) / (l_center + l_edge)

# ==========================================
# 單張照片處理模組：計算指標 + 儲存六宮格圖表
# ==========================================
def analyze_and_plot(image_path, output_folder):
    img = cv2.imread(image_path)
    if img is None: return None
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = detector(gray)
    if len(faces) == 0: return None

    face = faces[0]
    landmarks = predictor(gray, face)
    def get_pt(idx): return (landmarks.part(idx).x, landmarks.part(idx).y)

    # --- 1. 背景學術運算 ---
    norm_pts = geometric_normalization(landmarks)
    gri_score = calculate_gri(norm_pts)
    ai_score = calculate_advanced_ai(norm_pts)
    yaw_score, pitch_score = calculate_pose_indices(norm_pts)
    lci_score = calculate_lci(gray, landmarks)

    # 基礎像素計算
    pt_left_cheek, pt_right_cheek = get_pt(1), get_pt(15)
    pt_brow_mid, pt_upper_lip = get_pt(27), get_pt(51)
    pt_nose_tip = get_pt(30)
    pt_left_eye, pt_right_eye = get_pt(36), get_pt(45)
    pt_chin = get_pt(8)
    pt_nose_base = get_pt(33)
    pt_mouth_l, pt_mouth_r = get_pt(48), get_pt(54)
    pt_nose_l, pt_nose_r = get_pt(31), get_pt(35)

    width_px = math.dist(pt_left_cheek, pt_right_cheek)
    height_px = math.dist(pt_brow_mid, pt_upper_lip)
    fwhr_raw = width_px / height_px if height_px != 0 else 0
    nx = pt_nose_tip[0]
    dist_l_px, dist_r_px = abs(nx - pt_left_eye[0]), abs(pt_right_eye[0] - nx)
    offset_px = abs(dist_l_px - dist_r_px)

    # --- 2. 準備 6 張獨立畫布並畫圖 ---
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    imgs = [img_rgb.copy() for _ in range(6)]
    img_fwhr, img_asym, img_yaw, img_pitch, img_gri, img_lci = imgs
    font = cv2.FONT_HERSHEY_SIMPLEX

    # 底層高對比標靶點
    for canvas in imgs:
        for i in range(68):
            pt = get_pt(i)
            cv2.circle(canvas, pt, 4, (0, 0, 0), -1, cv2.LINE_AA)
            cv2.circle(canvas, pt, 2, (0, 255, 255), -1, cv2.LINE_AA)
            cv2.circle(canvas, pt, 1, (0, 0, 0), -1, cv2.LINE_AA)

    # 圖 1：fWHR
    cv2.line(img_fwhr, pt_left_cheek, pt_right_cheek, (255, 255, 0), 2, cv2.LINE_AA)
    cv2.line(img_fwhr, pt_brow_mid, pt_upper_lip, (255, 0, 255), 2, cv2.LINE_AA)
    for p in [pt_left_cheek, pt_right_cheek, pt_brow_mid, pt_upper_lip]: draw_med_pt(img_fwhr, p, (255, 255, 255))
    draw_clear_text(img_fwhr, f"fWHR = {fwhr_raw:.3f}", (15, 40), font, 3, (255, 255, 0), 2)

    # 圖 2：Asymmetry
    img_h = img.shape[0]
    cv2.line(img_asym, (nx, 0), (nx, img_h), (0, 255, 0), 2, cv2.LINE_AA)
    cv2.line(img_asym, pt_left_eye, (nx, pt_left_eye[1]), (255, 165, 0), 2, cv2.LINE_AA)
    cv2.line(img_asym, pt_right_eye, (nx, pt_right_eye[1]), (0, 255, 255), 2, cv2.LINE_AA)
    for p in [pt_nose_tip, pt_left_eye, pt_right_eye]: draw_med_pt(img_asym, p, (255, 255, 255))
    draw_clear_text(img_asym, f"Offset = {offset_px:.1f}px", (15, 40), font, 3, (0, 255, 0), 2)

    # 圖 3：Yaw
    cv2.line(img_yaw, (nx, 0), (nx, img_h), (100, 100, 100), 2, cv2.LINE_AA)
    cv2.line(img_yaw, pt_nose_tip, (pt_left_cheek[0], pt_nose_tip[1]), (255, 100, 100), 3, cv2.LINE_AA)
    cv2.line(img_yaw, pt_nose_tip, (pt_right_cheek[0], pt_nose_tip[1]), (100, 200, 255), 3, cv2.LINE_AA)
    draw_med_pt(img_yaw, pt_nose_tip, (255, 255, 255))
    draw_clear_text(img_yaw, f"Yaw Index = {yaw_score:.3f}", (15, 40), font, 3, (100, 200, 255), 2)

    # 圖 4：Pitch
    offset = 40
    cv2.line(img_pitch, (pt_brow_mid[0]+offset, pt_brow_mid[1]), (pt_brow_mid[0]+offset, pt_nose_base[1]), (255, 0, 255), 3, cv2.LINE_AA)
    cv2.line(img_pitch, (pt_brow_mid[0]+offset, pt_nose_base[1]), (pt_brow_mid[0]+offset, pt_chin[1]), (0, 255, 0), 3, cv2.LINE_AA)
    draw_clear_text(img_pitch, f"Pitch Index = {pitch_score:.3f}", (15, 40), font, 3, (255, 0, 255), 2)

    # 圖 5：GRI
    cv2.line(img_gri, pt_brow_mid, pt_chin, (255, 150, 255), 2, cv2.LINE_AA)
    cv2.line(img_gri, pt_left_cheek, pt_right_cheek, (255, 255, 100), 2, cv2.LINE_AA)
    cv2.line(img_gri, pt_mouth_l, pt_mouth_r, (100, 255, 255), 2, cv2.LINE_AA)
    cv2.line(img_gri, pt_nose_l, pt_nose_r, (100, 255, 100), 2, cv2.LINE_AA)
    draw_clear_text(img_gri, f"GRI Score = {gri_score:.3f}", (15, 40), font, 3, (255, 255, 100), 2)

    # 圖 6：LCI
    for pt_idx in range(27, 31):
        cv2.circle(img_lci, get_pt(pt_idx), 8, (0, 0, 0), -1, cv2.LINE_AA)
        cv2.circle(img_lci, get_pt(pt_idx), 5, (0, 255, 255), -1, cv2.LINE_AA)
    for pt_idx in [2, 3, 13, 14]:
        cv2.circle(img_lci, get_pt(pt_idx), 8, (0, 0, 0), -1, cv2.LINE_AA)
        cv2.circle(img_lci, get_pt(pt_idx), 5, (255, 100, 100), -1, cv2.LINE_AA)
    draw_clear_text(img_lci, f"LCI Score = {lci_score:.3f}", (15, 40), font, 3, (255, 150, 100), 2)

    # --- 3. 將六宮格排版並存檔 (無聲運算模式，不彈出視窗) ---
    fig, axes = plt.subplots(2, 3, figsize=(24, 16))
    ax = axes.flatten()
    titles = ["1. fWHR", "2. Asymmetry", "3. Pose (Yaw)", "4. Pose (Pitch)", "5. GRI (Golden Ratio)", "6. LCI (Light Contrast)"]
    images = [img_fwhr, img_asym, img_yaw, img_pitch, img_gri, img_lci]

    for i in range(6):
        ax[i].imshow(images[i])
        ax[i].set_title(titles[i], fontsize=18, fontweight='bold', pad=15)
        ax[i].axis('off')

    plt.tight_layout()
    # 存檔並釋放記憶體
    base_filename = os.path.basename(image_path)
    save_path = os.path.join(output_folder, f"Analysis_{base_filename}")
    plt.savefig(save_path, dpi=150)
    plt.close(fig)

    # 回傳該圖片的所有指標，準備寫入 Excel
    return {"fWHR": fwhr_raw, "Yaw": yaw_score, "Pitch": pitch_score, "GRI": gri_score, "LCI": lci_score, "AI": ai_score}

# ==========================================
# 核心批次控制器：成對處理、存圖、算總指標
# ==========================================
def batch_process_and_summarize(photo_folder):
    output_folder = os.path.join(photo_folder, "results_plots")
    os.makedirs(output_folder, exist_ok=True)

    # 尋找所有結尾是 a.jpg 的基準照片
    baseline_files = glob.glob(os.path.join(photo_folder, "*a.jpg"))
    results = []

    print(f"🚀 開始實驗室級批次處理！偵測到 {len(baseline_files)} 位學生樣本...")
    print(f"📂 六宮格視覺化圖表將會自動儲存至: {os.path.abspath(output_folder)}\n")

    for a_path in sorted(baseline_files):
        student_id = os.path.basename(a_path).replace("a.jpg", "")
        b_path = a_path.replace("a.jpg", "b.jpg")

        if not os.path.exists(b_path):
            print(f"⚠️ 學生 {student_id} 缺少自拍照 (b.jpg)，跳過處理。")
            continue

        print(f"⏳ 正在處理學生 {student_id} 的證件照與自拍照...")

        # 處理並自動存圖
        data_a = analyze_and_plot(a_path, output_folder)
        data_b = analyze_and_plot(b_path, output_folder)

        if data_a and data_b:
            entry = {"Student_ID": student_id}
            for metric in ["fWHR", "Yaw", "Pitch", "GRI", "LCI", "AI"]:
                entry[f"{metric}_A (證件照)"] = data_a[metric]
                entry[f"{metric}_B (自拍照)"] = data_b[metric]
                entry[f"Delta_{metric} (變化量)"] = data_b[metric] - data_a[metric]
            results.append(entry)
            print(f"   ✅ 學生 {student_id} 處理完成，圖表已儲存。")
        else:
            print(f"   ❌ 學生 {student_id} 影像無法辨識人臉。")

    # --- 計算並印出全班的「總指標統計」 ---
    df = pd.DataFrame(results)
    if not df.empty:
        csv_path = os.path.join(photo_folder, "Final_Student_Dataset.csv")
        df.to_csv(csv_path, index=False, encoding="utf_8_sig")
        print("\n" + "="*60)
        print("🎯 【全班總指標統計 (Population Summary)】")
        print("="*60)
        print("以下為所有配對樣本的平均值 (Mean Metrics)：\n")

        for metric in ["fWHR", "Yaw", "Pitch", "GRI", "LCI", "AI"]:
            mean_a = df[f"{metriric}_B (自拍照)"].mean()
            mean_delta = df[f"Dec}_A (證件照)"].mean()
            mean_b = df[f"{metlta_{metric} (變化量)"].mean()
            print(f"📌 {metric:5s} | 證件照平均: {mean_a:6.3f} | 自拍照平均: {mean_b:6.3f} | 平均變化量: {mean_delta:+6.3f}")

        print("="*60)
        print("🎉 恭喜！所有運算完畢。")
        print(f"📊 原始數據大表已儲存為: {os.path.abspath(csv_path)}")
        print(f"🖼️ 所有學生的專屬分析圖已儲存於: {os.path.abspath(output_folder)}")
    else:
        print("\n❌ 沒有成功處理任何配對資料，請確認資料夾中是否有正確命名的相片檔案 (例如: 01a.jpg, 01b.jpg)。")

# 執行指令 (路徑設定為 "." 代表當下所在的資料夾)
batch_process_and_summarize(".")