# -*- coding: utf-8 -*-
"""实现“不同成效群组之六大面部特征机率密度分布图”的程序

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GmHulNJonxK-K9Q92egEm8piptO8_NSC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as stats
import os
import urllib.request

# ==========================================
# 准备 Colab 中文字体 (避免图表中文变方块)
# ==========================================
font_path = "TaipeiSansTCBeta-Regular.ttf"
if not os.path.exists(font_path):
    print("📥 正在下载中文字体...")
    urllib.request.urlretrieve("https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download", font_path)

import matplotlib.font_manager as fm
fm.fontManager.addfont(font_path)
plt.rcParams['font.family'] = 'Taipei Sans TC Beta'
plt.rcParams['axes.unicode_minus'] = False # 确保负号显示正常

# ==========================================
# 阶段 4：读取数据、计算 POMP 分数与卷标分组
# ==========================================
def process_pomp_and_grouping(csv_file="Final_Student_Dataset.csv"):
    if not os.path.exists(csv_file):
        print(f"❌ 找不到 {csv_file}！请确认你已经上传填好分数的 CSV 档案。")
        return None

    df = pd.read_csv(csv_file)

    # 检查是否有分数字段并过滤掉没有填分数的学生
    if '学生照分数(b)' not in df.columns or '个人照分数(a)' not in df.columns:
        print("❌ CSV 中找不到分数字段，请确认域名。")
        return None

    df_clean = df.dropna(subset=['学生照分数(b)', '个人照分数(a)']).copy()

    if len(df_clean) == 0:
        print("❌ 没有读取到任何有效的分数，请确认是否填入了数字。")
        return None

    print(f"🚀 开始处理阶段四：读取到 {len(df_clean)} 位同学的有效分数。")

    # 计算 POMP Score
    df_clean['POMP_Score'] = (df_clean['个人照分数(a)'] - df_clean['学生照分数(b)']) / (10 - df_clean['学生照分数(b)'] + 1e-5)

    # 计算中位数并分组
    median_pomp = df_clean['POMP_Score'].median()
    df_clean['Group'] = (df_clean['POMP_Score'] >= median_pomp).astype(int)

    # 【学术命名】赋予高质感的组名
    df_clean['群组标签'] = df_clean['Group'].map({
        1: '高成效策略群组 (赢家)',
        0: '次佳策略群组 (一般)'
    })

    # 储存带有分组结果的新 CSV
    output_csv = "Final_Student_Dataset_Grouped.csv"
    df_clean.to_csv(output_csv, index=False, encoding='utf_8_sig')

    print("\n✅ [阶段四完成] POMP 分数与群组切分完毕！")
    print(f"📊 POMP 中位数为: {median_pomp:.3f}")
    print(f"🏆 高成效策略群组人数: {sum(df_clean['Group']==1)} 人")
    print(f"📉 次佳策略群组人数: {sum(df_clean['Group']==0)} 人")
    print(f"📁 分组名单已另存为: {output_csv} (你可以打开来看谁在哪个群组)\n")

    return df_clean

# ==========================================
# 阶段 5：高斯单纯贝氏模型 (绘制 6 宫格统计图)
# ==========================================
def plot_bayesian_gaussian(df):
    print("🧠 启动阶段五：构建高斯贝氏机率模型...")

    features = ["fWHR", "Yaw", "Pitch", "GRI", "LCI", "AI"]
    titles = ['fWHR (脸型宽高)', 'Yaw (水平转头)', 'Pitch (俯仰低头)', 'GRI (黄金比例)', 'LCI (光影对比)', 'AI (不对称度)']

    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    axes = axes.flatten()

    for i, metric in enumerate(features):
        ax = axes[i]
        col_name = f"LogRatio_{metric} (对数变形率)"

        # 提取两组的对数变形率数据
        data_high = df[df['Group'] == 1][col_name]
        data_low = df[df['Group'] == 0][col_name]

        # 计算期望值(mu)与标准偏差(std)
        mu1, std1 = data_high.mean(), max(data_high.std(), 1e-3)
        mu0, std0 = data_low.mean(), max(data_low.std(), 1e-3)

        # 设定 X 轴绘图范围
        x_min = min(data_high.min(), data_low.min())
        x_max = max(data_high.max(), data_low.max())
        margin = (x_max - x_min) * 0.2 if x_max != x_min else 0.1
        x_axis = np.linspace(x_min - margin, x_max + margin, 200)

        # 绘制高成效组 (红线)
        pdf_high = stats.norm.pdf(x_axis, mu1, std1)
        ax.plot(x_axis, pdf_high, color='#e74c3c', lw=3, label='高成效策略群组 (赢家)')
        ax.fill_between(x_axis, pdf_high, color='#e74c3c', alpha=0.2)

        # 绘制次佳策略组 (蓝虚线)
        pdf_low = stats.norm.pdf(x_axis, mu0, std0)
        ax.plot(x_axis, pdf_low, color='#3498db', lw=2, linestyle='--', label='次佳策略群组 (一般)')
        ax.fill_between(x_axis, pdf_low, color='#3498db', alpha=0.1)

        # 图表美化
        ax.set_title(f"【{titles[i]}】 策略分布 (机率密度)", fontsize=15, fontweight='bold', pad=10)
        ax.set_xlabel("对数变形率 (Log-Ratio) \n <0:缩小/减少 | =0:无变化 | >0:放大/增加", fontsize=10)
        ax.set_ylabel("机率密度 (PDF)", fontsize=10)

        # 标注 mu 数值框
        textstr = f"高成效 $\\mu$={mu1:.3f}\n次佳组 $\\mu$={mu0:.3f}"
        props = dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='gray')
        ax.text(0.05, 0.95, textstr, transform=ax.transAxes, fontsize=11,
                verticalalignment='top', bbox=props)

        if i == 0:
            ax.legend(loc='lower left', fontsize=11)

    plt.suptitle("6D 高斯单纯贝氏模型：自拍修图策略成效之机率密度解析", fontsize=22, fontweight='bold', y=0.95)
    plt.tight_layout(rect=[0, 0, 1, 0.93])

    # 储存图表
    save_path = "Bayesian_6D_Gaussian_Comparison.png"
    plt.savefig(save_path, dpi=300)
    plt.close(fig)
    print(f"✅ [阶段五完成] 完美对比的 6 宫格统计图已生成：{save_path}")

# ==========================================
# 主程序执行区
# ==========================================
df_grouped = process_pomp_and_grouping("Final_Student_Dataset.csv")

if df_grouped is not None:
    plot_bayesian_gaussian(df_grouped)