# -*- coding: utf-8 -*-
"""实现“单维策略达成高成效策略群组之概率分析”的程序

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13xXCGAoThjNjyJDKrVemynDn1-DoA3dc
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os
import urllib.request
import matplotlib.font_manager as fm

# ==========================================
# 准备 Colab 中文字体
# ==========================================
font_path = "TaipeiSansTCBeta-Regular.ttf"
if not os.path.exists(font_path):
    print("📥 正在下载中文字体...")
    urllib.request.urlretrieve("https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download", font_path)

fm.fontManager.addfont(font_path)
plt.rcParams['font.family'] = 'Taipei Sans TC Beta'
plt.rcParams['axes.unicode_minus'] = False

# ==========================================
# 条件机率策略分析
# ==========================================
def calculate_conditional_probabilities(csv_file="Final_Student_Dataset_Grouped.csv"): # 请确保档名符合你前一步的输出
    if not os.path.exists(csv_file):
        # 容错处理：如果找不到菁英版，找一般版
        csv_file = "Final_Student_Dataset.csv"
        if not os.path.exists(csv_file):
            print(f"❌ 找不到资料档!请确认是否有先执行阶段四。")
            return

    df = pd.read_csv(csv_file)

    # 确保有 Group 栏位 (1=高成效, 0=次佳)
    if 'Group' not in df.columns:
        print("❌ 资料中缺乏 'Group' 分组标签，请确认阶段四是否正确执行。")
        return

    total_students = len(df)
    winners = sum(df['Group'] == 1)
    base_prob = winners / total_students

    print("="*60)
    print("🎯 【自拍修图策略：条件机率与胜率分析】")
    print("="*60)
    print(f"👥 总样本数: {total_students} 人")
    print(f"🏆 高成效群组: {winners} 人")
    print(f"🎲 基础盲抽胜率 P(赢家): {base_prob:.1%}")
    print("-" * 60)

    # 1. 定义修图动作事件 (将连续数值转化为条件)
    # 取中位数以上的变动视为「有采用该策略」，以确保每个条件都有足够样本
    actions = {
        '脸型缩窄 (fWHR < 中位)': df['LogRatio_fWHR (对数变形率)'] < df['LogRatio_fWHR (对数变形率)'].median(),
        '侧脸转头 (Yaw > 中位)': df['LogRatio_Yaw (对数变形率)'] > df['LogRatio_Yaw (对数变形率)'].median(),
        '微抬下颚 (Pitch > 0)': df['LogRatio_Pitch (对数变形率)'] > 0,
        '趋近公版比例 (GRI > 0)': df['LogRatio_GRI (对数变形率)'] > 0,
        '增强光影 (LCI > 0)': df['LogRatio_LCI (对数变形率)'] > 0,
        '保留不对称真实感 (AI > 中位)': df['LogRatio_AI (对数变形率)'] > df['LogRatio_AI (对数变形率)'].median()
    }

    results = []

    # 2. 计算单一条件机率 P(赢家 | 策略)
    print("🔍 [单一策略条件胜率]")
    for action_name, condition in actions.items():
        subset = df[condition]
        n_condition = len(subset)

        if n_condition > 0:
            n_win_given_condition = sum(subset['Group'] == 1)
            prob = n_win_given_condition / n_condition
            gain = prob - base_prob

            results.append({
                '策略': action_name,
                '采用人数': n_condition,
                '条件胜率': prob,
                '胜率提升': gain
            })

            # 印出结果
            trend = "🔥 提升" if gain > 0 else "📉 下降"
            print(f"👉 策略: {action_name:<20} | 采用:{n_condition:2d}人 | 胜率: P(赢家|此策略) = {prob:>5.1%} | {trend} {abs(gain):>5.1%}")

    # 转为 DataFrame 方便排序与画图
    res_df = pd.DataFrame(results).sort_values(by='条件胜率', ascending=False)

    # 3. 寻找黄金组合技 (任选胜率前两名的策略做交集)
    print("-" * 60)
    print("🏆 [黄金组合技：联合条件机率]")

    best_strategy_1 = res_df.iloc[0]['策略']
    best_strategy_2 = res_df.iloc[1]['策略']

    cond_1 = actions[best_strategy_1]
    cond_2 = actions[best_strategy_2]
    joint_condition = cond_1 & cond_2

    subset_joint = df[joint_condition]
    n_joint = len(subset_joint)

    if n_joint > 0:
        prob_joint = sum(subset_joint['Group'] == 1) / n_joint
        print(f"✨ 组合条件: {best_strategy_1} ∩ {best_strategy_2}")
        print(f"   采用此组合人数: {n_joint} 人")
        print(f"   🚀 联合条件胜率 P(赢家 | 组合技) = {prob_joint:.1%}")
        print(f"   (相较基础胜率提升了: {prob_joint - base_prob:+.1%})")
    else:
        print("⚠️ 样本中没有人同时采用最强的两个策略。")
    print("="*60)

    # ==========================================
    # 绘制胜率对比长条图
    # ==========================================
    plt.figure(figsize=(10, 6))

    # 准备画图数据 (加入基础胜率与组合技)
    plot_labels = ['基础胜率 (无策略)'] + res_df['策略'].tolist()
    plot_probs = [base_prob] + res_df['条件胜率'].tolist()
    colors = ['gray'] + ['#e74c3c' if p > base_prob else '#3498db' for p in res_df['条件胜率']]

    if n_joint > 0:
        plot_labels.append('👑 黄金组合')
        plot_probs.append(prob_joint)
        colors.append('gold')

    bars = plt.barh(plot_labels[::-1], plot_probs[::-1], color=colors[::-1])

    # 加上数值标签与基准线
    plt.axvline(x=base_prob, color='black', linestyle='--', linewidth=1.5, label=f'基础胜率基准线 ({base_prob:.1%})')

    for bar in bars:
        width = bar.get_width()
        plt.text(width + 0.01, bar.get_y() + bar.get_height()/2, f'{width:.1%}',
                 va='center', fontsize=11, fontweight='bold')

    plt.title("自拍修图策略：条件胜率 (Conditional Probability) 提升分析", fontsize=16, fontweight='bold', pad=15)
    plt.xlabel("高成效群组胜率 P(Win | Strategy)", fontsize=12)
    plt.xlim(0, max(plot_probs) + 0.15) # 留空间给标签
    plt.legend(loc='lower right')
    plt.tight_layout()

    save_path = "Strategy_WinRate_Analysis.png"
    plt.savefig(save_path, dpi=300)
    plt.show()

    print(f"✅ 胜率对比图表已储存为：{save_path}")

# 执行分析 (请确认你的档名是这个，如果不同请修改)
calculate_conditional_probabilities("Final_Student_Dataset_Grouped.csv")