# -*- coding: utf-8 -*-
"""实现“多维策略达成高成效策略群组之概率分析”的程序

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JZkTrtDrwFynb8gT3qWyoKFoyfwzhVta
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import itertools
import os
import urllib.request
import matplotlib.font_manager as fm

# ==========================================
# 准备 Colab 中文字体
# ==========================================
font_path = "TaipeiSansTCBeta-Regular.ttf"
if not os.path.exists(font_path):
    print("📥 正在下载中文字体...")
    urllib.request.urlretrieve("https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download", font_path)

fm.fontManager.addfont(font_path)
plt.rcParams['font.family'] = 'Taipei Sans TC Beta'
plt.rcParams['axes.unicode_minus'] = False

# ==========================================
# 多策略联合条件机率分析
# ==========================================
def multi_strategy_analysis(csv_file="Final_Student_Dataset_Grouped.csv"):
    if not os.path.exists(csv_file):
        print(f"❌ 找不到 {csv_file}！")
        return

    df = pd.read_csv(csv_file)

    if 'Group' not in df.columns:
        print("❌ 找不到 Group 栏位。")
        return

    base_prob = sum(df['Group'] == 1) / len(df)
    print("="*65)
    print("🌟 【进阶分析：多策略黄金组合 (Joint Conditional Probability)】")
    print("="*65)
    print(f"🎲 全班基准胜率 P(高成效): {base_prob:.1%}\n")

    # 1. 定义 6 种基础的明确「修图动作」 (LogRatio > 0 代表放大/增加，< 0 代表缩小)
    actions = {
        '缩窄脸部': df['LogRatio_fWHR (对数变形率)'] < 0,
        '增加侧脸': df['LogRatio_Yaw (对数变形率)'] > 0,
        '微抬下颚': df['LogRatio_Pitch (对数变形率)'] > 0,
        '趋近公版比例': df['LogRatio_GRI (对数变形率)'] > 0,
        '增强光影': df['LogRatio_LCI (对数变形率)'] > 0,
        '保留不对称': df['LogRatio_AI (对数变形率)'] > 0
    }

    action_names = list(actions.keys())
    results = []

    # 设定防呆门槛：至少要有 3 个人同时采用这套组合技，才具备基本统计意义
    min_support = 3

    # 2. 生成所有 2 个一组 (C 6 取 2 = 15) 与 3 个一组 (C 6 取 3 = 20) 的组合
    combos_2 = list(itertools.combinations(action_names, 2))
    combos_3 = list(itertools.combinations(action_names, 3))
    all_combos = combos_2 + combos_3

    print(f"🔍 程序开始扫描 {len(combos_2)} 组双策略与 {len(combos_3)} 组三策略...\n")

    # 3. 遍历每一种组合，计算联合条件机率 P(Win | A ∩ B ∩ C)
    for combo in all_combos:
        # 将组合内的条件做「交集 (AND)」
        joint_condition = actions[combo[0]]
        for i in range(1, len(combo)):
            joint_condition = joint_condition & actions[combo[i]]

        subset = df[joint_condition]
        n_users = len(subset)

        # 只记录超过最小支持度门槛的组合
        if n_users >= min_support:
            n_winners = sum(subset['Group'] == 1)
            prob = n_winners / n_users

            results.append({
                '组合名称': " + ".join(combo),
                '策略数量': len(combo),
                '采用人数': n_users,
                '联合胜率': prob,
                '胜率提升': prob - base_prob
            })

    # 4. 整理数据并排序 (胜率由高到低，若胜率相同则看采用人数)
    res_df = pd.DataFrame(results)

    if res_df.empty:
        print("⚠️ 样本分布过于分散，没有任何多策略组合达到至少 3 人的采用门槛。")
        return

    res_df = res_df.sort_values(by=['联合胜率', '采用人数'], ascending=[False, False]).reset_index(drop=True)

    # 印出 Top 10 强力组合
    print("🏆 【胜率排行榜 Top 10 组合技】")
    for idx, row in res_df.head(10).iterrows():
        trend = "🔥 提升" if row['胜率提升'] > 0 else "📉 下降"
        print(f"No.{idx+1:02d} | 👥 {row['采用人数']:2d}人 | 胜率: {row['联合胜率']:>5.1%} | {trend} {abs(row['胜率提升']):>5.1%} | {row['组合名称']}")
    print("-" * 65)

    # ==========================================
    # 绘制多策略胜率长条图 (取 Top 10)
    # ==========================================
    plot_df = res_df.head(10).iloc[::-1] # 反转顺序让第一名在最上面

    plt.figure(figsize=(12, 7))
    colors = ['#e74c3c' if p > base_prob else '#3498db' for p in plot_df['联合胜率']]

    bars = plt.barh(plot_df['组合名称'], plot_df['联合胜率'], color=colors, edgecolor='black')

    # 基准线
    plt.axvline(x=base_prob, color='gray', linestyle='--', linewidth=2, label=f'全班基准胜率 ({base_prob:.1%})')

    # 标签
    for bar, n_users in zip(bars, plot_df['采用人数']):
        width = bar.get_width()
        plt.text(width + 0.01, bar.get_y() + bar.get_height()/2,
                 f"{width:.1%} (N={n_users})",
                 va='center', fontsize=11, fontweight='bold')

    plt.title(f"多策略黄金组合分析 (联合条件机率) - 仅显示采用人数 ≥ {min_support} 人之组合", fontsize=16, fontweight='bold', pad=15)
    plt.xlabel("高成效群组胜率 P(Win | 组合策略)", fontsize=12)
    plt.xlim(0, max(plot_df['联合胜率'].max(), base_prob) + 0.15)
    plt.legend(loc='lower right')
    plt.tight_layout()

    save_path = "Multi_Strategy_Joint_Probability.png"
    plt.savefig(save_path, dpi=300)
    plt.show()
    print(f"✅ 多策略胜率分析图已生成：{save_path}")

# 执行分析
multi_strategy_analysis("Final_Student_Dataset_Grouped.csv")