# -*- coding: utf-8 -*-
"""实现“模型三:基于欧氏距离之个体相似度评估模型与个性化策略推荐”之程序.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QIzXwv-jpnPag0FyqHf9fNrgoZE_u_iP
"""

import os
import math
import urllib.request
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as stats
from sklearn.preprocessing import StandardScaler

# ==========================================
# ⚙️ 系统设定区
# ==========================================
TARGET_CSV_FILE = "Final_Student_Dataset_Grouped.csv"
COL_STUDENT_SCORE = '学生照分数(b)'
COL_SELFIE_SCORE = '个人照分数(a)'

# ==========================================
# 初始设定：准备 Colab 中文字体
# ==========================================
font_path = "TaipeiSansTCBeta-Regular.ttf"
if not os.path.exists(font_path):
    print("📥 正在下载中文字体...")
    urllib.request.urlretrieve("https://drive.google.com/uc?id=1eGAsTN1HBpJAkeVM57_C7ccp7hbgSz3_&export=download", font_path)

import matplotlib.font_manager as fm
fm.fontManager.addfont(font_path)
plt.rcParams['font.family'] = 'Taipei Sans TC Beta'
plt.rcParams['axes.unicode_minus'] = False

# ==========================================
# 阶段 4：读取数据、计算 POMP 分数与标签分组
# ==========================================
def process_pomp_and_grouping(csv_file):
    if not os.path.exists(csv_file):
        print(f"❌ 找不到 {csv_file}！请确认你已经上传文件。")
        return None

    df = pd.read_csv(csv_file)

    if COL_STUDENT_SCORE not in df.columns or COL_SELFIE_SCORE not in df.columns:
        print(f"❌ 错误：在 CSV 中找不到名为 '{COL_STUDENT_SCORE}' 的列。")
        return None

    df_clean = df.dropna(subset=[COL_STUDENT_SCORE, COL_SELFIE_SCORE]).copy()
    print(f"\n🚀 [阶段四] 成功读取到 {len(df_clean)} 位同学的有效分数。")

    df_clean['POMP_Score'] = (df_clean[COL_SELFIE_SCORE] - df_clean[COL_STUDENT_SCORE]) / (10 - df_clean[COL_STUDENT_SCORE] + 1e-5)
    median_pomp = df_clean['POMP_Score'].median()
    df_clean['Group'] = (df_clean['POMP_Score'] >= median_pomp).astype(int)

    df_clean['群组标签'] = df_clean['Group'].map({
        1: '高成效策略群组 (赢家)',
        0: '次佳策略群组 (一般)'
    })

    output_csv = "Final_Student_Dataset_Analyzed.csv"
    df_clean.to_csv(output_csv, index=False, encoding='utf_8_sig')

    print(f"✅ POMP 中位数为: {median_pomp:.3f}")
    print(f"🏆 赢家池人数: {sum(df_clean['Group']==1)} 人 | 📉 次佳组人数: {sum(df_clean['Group']==0)} 人\n")

    return df_clean

# ==========================================
# 阶段 5：高斯单纯贝叶斯模型 (绘制 6 宫格统计图)
# ==========================================
def plot_bayesian_gaussian(df):
    print("🧠 [阶段五] 构建 6D 高斯贝叶斯概率模型绘图中...")

    base_metrics = ["fWHR", "Yaw", "Pitch", "GRI", "LCI", "AI"]
    titles = ['fWHR (脸型宽高)', 'Yaw (水平转头)', 'Pitch (俯仰低头)', 'GRI (黄金比例)', 'LCI (光影对比)', 'AI (不对称度)']

    fig, axes = plt.subplots(2, 3, figsize=(18, 12))
    axes = axes.flatten()

    for i, metric in enumerate(base_metrics):
        ax = axes[i]
        col_name = f"LogRatio_{metric} (对数变形率)"

        if col_name not in df.columns:
            continue

        data_high = df[df['Group'] == 1][col_name].dropna()
        data_low = df[df['Group'] == 0][col_name].dropna()

        mu1, std1 = data_high.mean(), max(data_high.std(), 1e-3)
        mu0, std0 = data_low.mean(), max(data_low.std(), 1e-3)

        x_min = min(data_high.min(), data_low.min())
        x_max = max(data_high.max(), data_low.max())
        margin = (x_max - x_min) * 0.2 if x_max != x_min else 0.1
        x_axis = np.linspace(x_min - margin, x_max + margin, 200)

        pdf_high = stats.norm.pdf(x_axis, mu1, std1)
        ax.plot(x_axis, pdf_high, color='#e74c3c', lw=3, label='高成效策略群组 (赢家)')
        ax.fill_between(x_axis, pdf_high, color='#e74c3c', alpha=0.2)

        pdf_low = stats.norm.pdf(x_axis, mu0, std0)
        ax.plot(x_axis, pdf_low, color='#3498db', lw=2, linestyle='--', label='次佳策略群组 (一般)')
        ax.fill_between(x_axis, pdf_low, color='#3498db', alpha=0.1)

        ax.set_title(f"【{titles[i]}】 策略分布", fontsize=15, fontweight='bold', pad=10)
        ax.set_xlabel("对数变形率 (Log-Ratio)", fontsize=10)
        ax.set_ylabel("概率密度 (PDF)", fontsize=10)

        textstr = f"高成效 $\\mu$={mu1:.3f}\n次佳组 $\\mu$={mu0:.3f}"
        props = dict(boxstyle='round', facecolor='white', alpha=0.8, edgecolor='gray')
        ax.text(0.05, 0.95, textstr, transform=ax.transAxes, fontsize=11, verticalalignment='top', bbox=props)

        if i == 0:
            ax.legend(loc='lower left', fontsize=11)

    plt.suptitle("6D 高斯单纯贝叶斯模型：自拍修图策略成效之概率密度解析", fontsize=22, fontweight='bold', y=0.95)
    plt.tight_layout(rect=[0, 0, 1, 0.93])

    save_path = "Bayesian_6D_Gaussian_Comparison.png"
    plt.savefig(save_path, dpi=300)
    plt.close(fig)
    print(f"✅ 完美对比的 6 宫格统计图已生成：{save_path}\n")

# ==========================================
# 阶段 6：个性化策略推荐系统 (欧氏距离与反推建议)
# ==========================================
def run_personalized_recommendation(df):
    print("🤖 [阶段六] 启动：个性化修图推荐系统 (K=1 匹配与物理反推)")

    base_metrics = ["fWHR", "Yaw", "Pitch", "GRI", "LCI", "AI"]

    # 取 ID照原生特征作为距离比对标准
    feature_cols = [f"{m}_ID(b.jpg)" for m in base_metrics]
    # 取对数变形率作为策略提取标准
    rfvr_cols = [f"LogRatio_{m} (对数变形率)" for m in base_metrics]

    winner_pool = df[df['Group'] == 1].copy()
    suboptimal_group = df[df['Group'] == 0].copy()

    scaler = StandardScaler()
    scaler.fit(df[feature_cols])
    winners_scaled = scaler.transform(winner_pool[feature_cols])
    suboptimal_scaled = scaler.transform(suboptimal_group[feature_cols])

    recommendation_results = []
    print(f"✅ 正在为 {len(suboptimal_group)} 位次佳组同学寻找几何双胞胎...\n")

    for i, (idx, user_row) in enumerate(suboptimal_group.iterrows()):
        user_z = suboptimal_scaled[i].reshape(1, -1)

        distances = np.linalg.norm(winners_scaled - user_z, axis=1)
        best_match_idx = np.argmin(distances)
        min_dist = distances[best_match_idx]

        twin_id = winner_pool.index[best_match_idx]
        twin_rfvr = winner_pool.loc[twin_id, rfvr_cols]
        u_orig = user_row[feature_cols]

        # 轨道一：实体动作
        ta_yaw = u_orig['Yaw_ID(b.jpg)'] * math.exp(twin_rfvr["LogRatio_Yaw (对数变形率)"])
        ta_yaw_clamped = max(0, min(ta_yaw, 0.99))
        u_yaw_clamped = max(0, min(u_orig['Yaw_ID(b.jpg)'], 0.99))
        delta_yaw_deg = math.degrees(math.asin(ta_yaw_clamped) - math.asin(u_yaw_clamped))
        yaw_dir = "向侧边(左/右)转动" if delta_yaw_deg > 0 else "脸部向正中央转回"

        ta_pitch = u_orig['Pitch_ID(b.jpg)'] * math.exp(twin_rfvr["LogRatio_Pitch (对数变形率)"])
        delta_pitch_deg = math.degrees(math.atan(ta_pitch) - math.atan(u_orig['Pitch_ID(b.jpg)']))
        pitch_dir = "相机抬高(或收下巴)" if delta_pitch_deg > 0 else "相机降低(或抬下巴)"

        # 轨道二：数字后期
        p_fwhr = (math.exp(twin_rfvr["LogRatio_fWHR (对数变形率)"]) - 1) * 100
        p_lci = (math.exp(twin_rfvr["LogRatio_LCI (对数变形率)"]) - 1) * 100

        # 预期优化目标
        p_gri = (math.exp(twin_rfvr["LogRatio_GRI (对数变形率)"]) - 1) * 100
        p_ai = (math.exp(twin_rfvr["LogRatio_AI (对数变形率)"]) - 1) * 100

        # 取出学号
        subject_id = user_row['Student_ID'] if 'Student_ID' in user_row else user_row.name
        twin_student_id = winner_pool.loc[twin_id, 'Student_ID'] if 'Student_ID' in winner_pool.columns else twin_id

        recommendation_results.append({
            "Subject_ID": subject_id,
            "Twin_ID": twin_student_id,
            "Distance": round(min_dist, 4),
            "Suggest_Yaw_Deg": round(delta_yaw_deg, 2),
            "Suggest_Pitch_Deg": round(delta_pitch_deg, 2),
            "Suggest_fWHR_Slider": round(p_fwhr, 2),
            "Suggest_LCI_Slider": round(p_lci, 2)
        })

        # 【解除封印】：将全班次佳组同学的报告全部打印出来！
        print(f"👤 测试者学号: {subject_id} (最相似赢家学号: {twin_student_id}, 距离: {min_dist:.4f})")
        print(f"   [轨道一：实体摄影端建议]")
        print(f"   ▶ 水平转动：{yaw_dir}约 {abs(delta_yaw_deg):.2f} 度")
        print(f"   ▶ 俯仰微调：{pitch_dir}约 {abs(delta_pitch_deg):.2f} 度")
        print(f"   [轨道二：数字 APP 后期参数]")
        print(f"   ▶ 脸宽拉杆：{'向右拉宽' if p_fwhr > 0 else '向左缩窄'} {abs(p_fwhr):.2f}%")
        print(f"   ▶ 光影对比：{'增强打亮' if p_lci > 0 else '柔化降低'} {abs(p_lci):.2f}%")
        print(f"   [预期整体美学目标]")
        if p_gri < 0: print(f"   ▶ 黄金比例 (GRI) 误差减少：{abs(p_gri):.2f}% (五官比例趋于和谐)")
        else: print(f"   ▶ 黄金比例 (GRI) 误差增加：{p_gri:.2f}% (往个人特色化方向发展)")
        if p_ai < 0: print(f"   ▶ 不对称度 (AI) 改善降低：{abs(p_ai):.2f}% (通过角度投影掩盖，让脸型更对称)")
        else: print(f"   ▶ 不对称度 (AI) 反向增加：{p_ai:.2f}% (通过角度掩盖与修正))")
        print("-" * 65)

    rec_df = pd.DataFrame(recommendation_results)
    rec_df.to_csv("Personalized_Optimization_Strategies.csv", index=False, encoding='utf_8_sig')
    print(f"📁 全班完整推荐策略清单已存档：Personalized_Optimization_Strategies.csv")
    print("=" * 65)

# ==========================================
# 🌟 主程序执行入口
# ==========================================
if __name__ == "__main__":
    print("=" * 65)
    print("🎓 启动专题分析主程序 🎓")
    print("=" * 65)

    df_grouped = process_pomp_and_grouping(TARGET_CSV_FILE)

    if df_grouped is not None:
        plot_bayesian_gaussian(df_grouped)
        run_personalized_recommendation(df_grouped)